# Generated by Django 3.0 on 2019-12-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dependencia',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
