# Generated by Django 3.0 on 2019-12-06 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('TAid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tipoactivo', models.CharField(choices=[('SW', 'Software'), ('HW', 'Hardware'), ('INF', 'Informació'), ('RRHH', 'RRHH'), ('SC', 'Servicios Contratados')], default='SW', max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('propietario', models.CharField(max_length=20)),
                ('responsable', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=20)),
                ('valor', models.CharField(choices=[('Leve', '1'), ('Leve', '2'), ('Grave', '4'), ('Crítico', '5'), ('Crítico', '6')], default='1', max_length=7)),
                ('rs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
