# Generated by Django 3.0 on 2020-01-23 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_auto_20191206_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='tipoactivo',
            field=models.CharField(choices=[('SW', 'Software'), ('HW', 'Hardware'), ('INF', 'Información'), ('RRHH', 'RRHH'), ('SC', 'Servicios Contratados')], default='SW', max_length=20),
        ),
        migrations.CreateModel(
            name='Amenaza',
            fields=[
                ('id_A', models.AutoField(primary_key=True, serialize=False)),
                ('riesgo', models.IntegerField()),
                ('a_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.Activo')),
            ],
        ),
    ]
