# Generated by Django 3.0 on 2020-01-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_auto_20200123_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenaza',
            name='riesgo',
        ),
        migrations.AlterField(
            model_name='amenaza',
            name='impacto',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
        migrations.AlterField(
            model_name='amenaza',
            name='prob',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1),
        ),
    ]
