# Generated by Django 3.0 on 2020-01-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_auto_20200123_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenaza',
            old_name='id_A',
            new_name='id_Amenaza',
        ),
        migrations.RenameField(
            model_name='amenaza',
            old_name='prob',
            new_name='probabilidad',
        ),
    ]
