# Generated by Django 3.0 on 2020-01-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0006_auto_20200123_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenaza',
            old_name='a_activo',
            new_name='activo',
        ),
    ]
