# Generated by Django 3.0 on 2020-01-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0008_amenaza_riesgo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenaza',
            name='riesgo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
