# Generated by Django 3.0 on 2020-01-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0009_auto_20200124_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenaza',
            name='riesgo',
        ),
        migrations.AddField(
            model_name='amenaza',
            name='amenaza',
            field=models.CharField(default='prueba', max_length=100),
            preserve_default=False,
        ),
    ]
