# Generated by Django 3.0 on 2020-02-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0010_auto_20200124_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='valor',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=7),
        ),
    ]
