# Generated by Django 3.0 on 2020-02-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_auto_20200220_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='informe',
            field=models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/%D/'),
        ),
    ]
