# Generated by Django 3.0 on 2020-02-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0012_activo_informe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='informe',
            field=models.FileField(blank=True, null=True, upload_to='documentos/%Y/'),
        ),
    ]
