# Generated by Django 3.0 on 2020-03-02 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0014_auto_20200227_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAmenaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_amenaza', models.CharField(max_length=100)),
                ('probabilidad', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('impacto', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('id_f_amenaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.Amenaza')),
            ],
        ),
    ]
