# Generated by Django 3.0 on 2020-03-09 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0015_historicoamenaza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenaza',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenazas_activo', to='activos.Activo'),
        ),
    ]
